USE	[Honse];

CREATE TABLE [ProductCategory](
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NONCLUSTERED,
	[Name] VARCHAR(MAX) NOT NULL,
	
	[UserId] UNIQUEIDENTIFIER NOT NULL REFERENCES [AspNetUsers]
)

CREATE TABLE [Product](
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NONCLUSTERED,
	
	[Name] VARCHAR(MAX) NOT NULL,
	[Description] VARCHAR(MAX) NOT NULL,
	[Price] DECIMAL(19, 4) NOT NULL,
	[VAT] DECIMAL(19, 4) NOT NULL,
	[Image] VARCHAR(MAX) NOT NULL,
	[IsEnabled] BIT NOT NULL,

	[UserId] UNIQUEIDENTIFIER NOT NULL REFERENCES [AspNetUsers],
	[CategoryId] UNIQUEIDENTIFIER NOT NULL REFERENCES [ProductCategory],
)