USE [Honse];

CREATE TABLE [OrderConfirmationToken](
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NONCLUSTERED,
	[UserId] UNIQUEIDENTIFIER NOT NULL REFERENCES [AspNetUsers],
	[RestaurantId] UNIQUEIDENTIFIER NOT NULL REFERENCES [Restaurant],
	[ClientName] NVARCHAR(255) NOT NULL,
    [ClientEmail] NVARCHAR(255) NOT NULL,
	[DeliveryAddress] NVARCHAR(MAX) NOT NULL,
	[Products] NVARCHAR(MAX) NOT NULL,
	[ExpiresAt] DATETIME2 NOT NULL,
	[Used] BIT NOT NULL
)
